Clin 3480 guide reference Gestionnaire de filtres
Ferlab-Ste-Justine/clin-docs pull request #7
Opened 2024-11-14 14:35 UTC by chetta19

2024-11-14 19:27 UTC, kstonge approved these changes

2024-11-14 19:27 UTC, kstonge commented on docs/docs-fr/qlin_genetic/filters_manager/filters_manager.md
> +L’icône crayon ![crayon](editicon.png)permet de modifier le nom du filtre pour le retrouver plus facilement ultérieurement.
Ajouter un espace après l'icône ici: ![crayon](editicon.png)permet

2024-11-14 19:27 UTC, kstonge commented on docs/docs-fr/qlin_genetic/filters_manager/filters_manager.md
> +Il est possible de modifier la jointure des critères en utilisant l’hyperlien **Et / Ou**.
C'est du micro détail, mais ici tu intègre la barre oblique dans le format "gras", alors que dans le paragraphe en dessous, la barre oblique n'est pas en gras. Ça serait bien d'harmoniser le tout.

2024-11-14 19:27 UTC, kstonge commented on docs/docs-fr/qlin_genetic/filters_manager/filters_manager.md
> +# Gestionnaire de filtres
À voir si tu veux parler du toggle "Champs" et du bouton "Tout effacer"
![image](https://github.com/user-attachments/assets/526981f7-1fef-4559-911b-fbee46b2e0c8)

2024-11-14 19:27 UTC, kstonge commented on docs/qlin_genetic/filters_manager/filters_manager.md
> +To create additional queries, use the **New Query** button or duplicate an existing query with the 📑 icon."
New **q**uery button

2024-11-14 19:27 UTC, kstonge commented on docs/qlin_genetic/filters_manager/filters_manager.md
> +To create additional queries, use the **New Query** button or duplicate an existing query with the 📑 icon."
Enlever les guillemets à la fin de la phrase.

2024-11-14 19:27 UTC, kstonge commented on docs/qlin_genetic/filters_manager/filters_manager.md
> +When selecting multiple queries using the checkboxes to the left of the query names (Q1, Q2, etc.), the **Combine** button allows you to create a new query with a join of the selected queries. The **
And / Or ne sont pas en gras comme en français.
Appliquer la même logique de "gras" uniformément:
- Soit avec la barre oblique en gras
- Soit la barre oblique exclue du gras

2024-11-15 18:04 UTC, kstonge requested changes

2024-11-15 18:04 UTC, kstonge commented on docs/docs-fr/qlin_genetic/filters_manager/filters_manager.md
> +### Supprimer toutes les requêtes
Est-ce qu'il manque cette section en anglais?

2024-11-15 18:41 UTC, chetta19 commented on docs/docs-fr/qlin_genetic/filters_manager/filters_manager.md
> +### Supprimer toutes les requêtes
oui. je viens de l'ajouté

2024-11-15 19:08 UTC, kstonge requested changes

2024-11-15 19:08 UTC, kstonge commented on docs/qlin_genetic/filters_manager/filters_manager.md
> +When there is more than one query, the **Clear All** hyperlink allows you to delete all queries with a single click.
the Clear **a**ll hyperlink

2024-11-18 16:12 UTC, kstonge approved these changes

2024-11-18 16:17 UTC, merged